---

- platform: mqtt
  name: "Office Light RGB"
  state_topic: "office/rgb1/light/status"
  command_topic: "office/rgb1/light/switch"
  brightness_state_topic: "office/rgb1/brightness/status"
  brightness_command_topic: "office/rgb1/brightness/set"
  rgb_state_topic: "office/rgb1/rgb/status"
  rgb_command_topic: "office/rgb1/rgb/set"
  effect_state_topic: "office/rgb1/effect/status"
  effect_command_topic: "office/rgb1/effect/set"
  effect_list:
    - rainbow
    - rainbow_with_glitter
    - confetti
    - sinelon
    - bpm
    - juggle
    - candycane
    - party_colors
    - rotate_party_colors
    - music_rainbow
    - music_rgb
    - music_rotate_party_colors
    - music_cycle
  qos: 0
  payload_on: "on"
  payload_off: "off"
  optimistic: false
